on:
  workflow_call:
    inputs:  
      username: 
        description: 'who-to-greet'
        default: 'World'
        required: true
        type: string
jobs:
  reuseable-job:
    runs-on: ubuntu-latest

    steps:
      name: Print the input name to STDOUT
      run: echos "Hello"  to the sonsole.
   
